[tools]
"aqua:suzuki-shunsuke/pinact" = "latest"
deno = "2.3"
gh = "latest"
"go:github.com/k1LoW/deck/cmd/deck" = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@lacolaco/mdtranslator" = "latest"
"npm:@openai/codex" = "latest"
ollama = "latest"
"pipx:openhands-ai" = "latest"
python = "latest"
uv = "latest"
watchexec = "latest"
"ubi:gitlab-org/cli" = { version = "latest", exe = "glab", provider = "gitlab" }

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

